#
# TWRP minimal-manifest 专用最小版本定义 (替代被裁掉的 AOSP version_defaults.mk).
# 注意: 只能设 RELEASE_PLATFORM_* , 不能直接设 PLATFORM_* (version_util.mk 会报错),
# BoardConfig 里原有的 PLATFORM_VERSION / PLATFORM_SECURITY_PATCH 在 product 配置阶段
# 覆盖, 不受影响.
#

RELEASE_PLATFORM_VERSION := 14
RELEASE_PLATFORM_SDK_VERSION := 34
RELEASE_PLATFORM_VERSION_CODENAME := REL
RELEASE_PLATFORM_VERSION_ALL_CODENAMES := REL
RELEASE_PLATFORM_VERSION_ALL_PREVIEW_CODENAMES :=
RELEASE_PLATFORM_VERSION_LAST_STABLE := 14
RELEASE_PLATFORM_VERSION_KNOWN_CODENAMES := REL
RELEASE_PLATFORM_SECURITY_PATCH := 2023-12-05
RELEASE_PLATFORM_SDK_EXTENSION_VERSION := 7
RELEASE_PLATFORM_VNDK_VERSION := 34
